<?php

namespace OC\PlatformBundle\Repository;

/**
 * TestslugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestslugRepository extends \Doctrine\ORM\EntityRepository
{
}
